spring.application.name=queue-service
spring.config.import=optional:configserver:

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
eureka.instance.prefer-ip-address=true
