spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id : patient-service
              uri: lb://PATIENT-SERVICE
              predicates:
                - Path= /patients/**

            - id: consultation-service
              uri: lb://CONSULTATION-SERVICE
              predicates:
                - Path= /consultation/**