spring.application.name=gateway-service
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
server.port=8080
spring.cloud.discovery.enabled=true




spring.security.oauth2.resourceserver.jwt.issuer-uri=http://3.84.72.92:8080/realms/cabinetX-microservice-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://3.84.72.92:8080/realms/cabinetX-microservice-realm/protocol/openid-connect/certs

management.endpoints.web.exposure.include=*
