spring.application.name=gateway-service
server.port=8080
spring.cloud.discovery.enabled=true




spring.security.oauth2.resourceserver.jwt.issuer-uri=http://3.84.72.92:8080/realms/cabinetX-microservice-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://3.84.72.92:8080/realms/cabinetX-microservice-realm/protocol/openid-connect/certs
