spring.application.name=payment-service
spring.cloud.config.uri=http://localhost:8888
spring.cloud.config.fail-fast=true
spring.config.import=optional:configserver:

Stripe configuration (override via environment variables or config server)
stripe.secret-key=sk_test_51Qazu9GdaDQ3aqADvKzWPkmE7o99TeDNt45TQcJHRSKZ2fMfRIqgzIpfHnEiPcYDNM4vTwSOyfLhc8eyFY4lTQYx00LF70zPbe
stripe.webhook-secret=whsec_EyQY5LK81vjIj0kCbjZ0jltzcPygiCNn
# Example plans
# stripe.plans.basic.price-id=price_xxx
# stripe.plans.basic.name=Premium Cabinet
# stripe.plans.basic.amount=250000
# stripe.plans.basic.currency=mad
# stripe.plans.basic.interval=month
